spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/dev_db?currentSchema=user_service}
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_pass}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  access-secret: ${ACCESS_SECRET_KEY}
  refresh-secret: ${REFRESH_SECRET_KEY}
  access-expiration: ${ACCESS_EXPIRATION}
  refresh-expiration: ${REFRESH_EXPIRATION}
