services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123
    volumes:
      - mongo_data_test:/data/db

volumes:
  mongo_data_test:
