spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

jwt:
  secret: ${JWT_ACCESS_SECRET}

logging:
  level:
    root: INFO
    com.marketplace.gateway: INFO
    org.springframework.cloud.gateway: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  forward-headers-strategy: framework