spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 2s

jwt:
  secret: "test-secret-key-test-secret-key-test-secret-key"

logging:
  level:
    root: WARN
    com.marketplace.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: health